### ISSUE TITLE
Grid media and media queries

### ISSUE THREAD

**Issue by dac09** [magicink/neat-components#1]
Hey, I'm struggling to understand how gridMedia works and should be used. The first argument is a grid, what is it's purpose? And in the example in the readme, the second argument is an array of css. When I try it out, I can see it applying the height, but any changes to the gridColumn inside it has no effect.

Would you kindly be able to supply another example? Perhaps a common example like take 12 columns on mobile, but take 6 columns on desktop?

Would apprecaite the help!

**Comment by magicink** [comment]
Sorry for taking so long to get back to you! Upon reading the documentation, I realize I documented this feature incorrectly and I will be publishing a new version shortly. As for the task you outlined, Here's how you would accomplish this:

```
// @flow
import React from 'react'
import styled, { ThemeProvider } from 'styled-components'
import Neat, {gridColumn, gridMedia, gridContainer} from '../../bundle'

const mobileGrid = Neat({
  columns: 12,
  gutter: '10px',
  media: 'only screen and (max-width: 600px)'
})

const desktopGrid = Neat({
  columns: 12,
  gutter: '20px',
  media: 'only screen and (min-width: 601px)'
})

const Column = styled.div`
  height: 50px;
  background-color: yellow;
  margin-top: 1rem;
  ${gridColumn(mobileGrid, 2)}
  ${gridMedia(desktopGrid, [
    {
      ...gridColumn(desktopGrid, 1),
      'background-color': 'red'
    },
  ])}
`

const Container = styled.div`
  ${gridContainer()}
`

export class GridMedia extends React.Component {
  render () {
    return [
      <h1 key={'header'}><code>gridMedia</code></h1>,
      <ThemeProvider key={'provider'} theme={Neat()}>
        <Container>
          <Column />
          <Column />
          <Column />
          <Column />
          <Column />
          <Column />
          <Column />
          <Column />
          <Column />
          <Column />
          <Column />
          <Column />
        </Container>
      </ThemeProvider>
    ]
  }
}
```

I'm going to include this example in the updated docs as well as with demos I'm including.

Thanks for your feedback.

**Comment by magicink** [comment]
I've included a demo in the repo. You can run the demo by running `npm run build:demo` followed by `npm run start:demo`
