### ISSUE TITLE
not an issue, just wanted to say that this rocks, amazing work and ill play with this today!

### ISSUE THREAD

**Issue by csantiago132** [magicink/neat-components#2]
Also, im assuming youre including a babel-polyfill? is conflicting with my environment.

**Comment by magicink** [comment]
I can remove this. Thanks for pointing this out.

**Comment by magicink** [comment]
I've remove `babel-polyfill`

**Comment by csantiago132** [comment]
Thanks! I’ll update the package!

**Comment by magicink** [comment]
I'm going to publish it to NPM as soon as I run it through a few tests.  Until then the fix is pushed up.
