### ISSUE TITLE
Grid Container mixin does not inject clearfix

### ISSUE THREAD

**Issue by vovadyach** [magicink/neat-components#4]
I found out that gridContainer() mixin does not work. It does not inject the clearfix. Please, check it.

**Comment by magicink** [comment]
Hi,

Can you show me how you are using it?

**Comment by magicink** [comment]
[Here](https://magicink.github.io/neat-components/docs/?selectedKind=Neat%20Components&selectedStory=9%2F3%20Column%20Grid&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) is an example of two grid containers stacked on top of each other. It appears to be passing the clearfix correctly.

**Comment by vovadyach** [comment]
Hi, here is the example:
import styled from 'styled-components';
import { gridContainer } from "neat-components";

const Wrapper = styled.div`
  ${gridContainer()}
`;

export default Wrapper; 

**and using:**

  <Wrapper>
          <Column>Product 1</Column>
          <Column>Product 2</Column>
          <Column>Product 3</Column>
          <Column>Product 4</Column>
        </Wrapper>

**Comment by magicink** [comment]
Thanks for catching this. I've pushed up a fix to NPM which should resolve the issue.

**Comment by vovadyach** [comment]
Thanks and welcome.
